{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "6068d952ee6b407cbbaaec56c283c094": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_eb0cbdfd7e054e5da55f9c9740a6239f",
            "max": 100,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_39fb0a2c1e2149d2aac9f4c0e4adb3ba",
            "value": 100
          }
        },
        "eb0cbdfd7e054e5da55f9c9740a6239f": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "auto"
          }
        },
        "39fb0a2c1e2149d2aac9f4c0e4adb3ba": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": "black",
            "description_width": ""
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "\n",
        "\n",
        "# **Data Engineeer Sandbox**\n"
      ],
      "metadata": {
        "id": "sydY6IPvnhrm"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## **Data Connection to Drive Folders**\n",
        "\n"
      ],
      "metadata": {
        "id": "LTSByLO_nX-Q"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Mount Google Drive to access the data files\n",
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rzvZpHZqcO2J",
        "outputId": "9762f11d-3ec2-479c-845a-c15f7544a962"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/drive\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Czy3sAvSdRd6",
        "outputId": "ed1ac6e2-9ae7-4528-cce2-bd895f0cfcbd"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Setup complete. Data path is: /content/drive/MyDrive/sdg_bc_sandbox/\n",
            "Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)\n",
            "\n",
            "--- Setup Complete ---\n"
          ]
        }
      ],
      "source": [
        "\n",
        "# Define the base path where the data is stored (adjust this path)\n",
        "DATA_PATH = '/content/drive/MyDrive/sdg_bc_sandbox/'\n",
        "\n",
        "print(\"Setup complete. Data path is:\", DATA_PATH)\n",
        "\n",
        "# Install DuckDB for simple, high-performance in-memory/file-based SQL (optional but recommended)\n",
        "!pip install duckdb\n",
        "print(\"\\n--- Setup Complete ---\")"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "db7a1bf3",
        "outputId": "ce2ca851-85b0-4e88-871c-0dc81dc8b7a6"
      },
      "source": [
        "import os\n",
        "\n",
        "# List contents of the DATA_PATH\n",
        "print(f\"Listing contents of {DATA_PATH}:\")\n",
        "for root, dirs, files in os.walk(DATA_PATH):\n",
        "    for file in files:\n",
        "        print(os.path.join(root, file))\n",
        "    for dir in dirs:\n",
        "        print(os.path.join(root, dir))"
      ],
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Listing contents of /content/drive/MyDrive/sdg_bc_sandbox/:\n",
            "/content/drive/MyDrive/sdg_bc_sandbox/Store_Territory.csv\n",
            "/content/drive/MyDrive/sdg_bc_sandbox/Customer.csv\n",
            "/content/drive/MyDrive/sdg_bc_sandbox/Currency.csv\n",
            "/content/drive/MyDrive/sdg_bc_sandbox/Product_Sales_20221231.csv\n",
            "/content/drive/MyDrive/sdg_bc_sandbox/Product_Sales_20210701.csv\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "## **Ingestion & Data Quality**"
      ],
      "metadata": {
        "id": "nWXP_Wc5oAgJ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import duckdb\n",
        "\n",
        "# Create a DuckDB connection\n",
        "con = duckdb.connect()\n",
        "version_duckdb = con.execute(\"SELECT version()\").fetchone()[0]\n",
        "print(f\" DuckDB  initialised successfully (Version: {version_duckdb}).\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "m1E9TiEzKCp8",
        "outputId": "4a88b92b-e1ee-4ead-a637-264b070d6bf1"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " DuckDB  initialised successfully (Version: v1.3.2).\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "### **Data ingestion (Bronze)**\n",
        "This section handles the ingestion of raw files from Google Drive into DuckDB.\n",
        "* The wildcard pattern `Product_Sales_*.csv` is used to automatically consolidate fragmented product sales files (`20210701` and `20221231`) into a single table with an optimised read operation.\n",
        "* Data is loaded with no changes in structure and field names to keep data as raw as possible before to apply any business logic in the next data layer (silver)."
      ],
      "metadata": {
        "id": "-oSj5ep9Mda3"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ==============================================================================\n",
        "# Creation of raw staging tables\n",
        "# ==============================================================================\n",
        "\n",
        "# Load the dataframes:\n",
        "\n",
        "try:\n",
        "  #customer\n",
        "  con.execute(f\"\"\"\n",
        "          CREATE OR REPLACE TABLE customers_raw AS\n",
        "          SELECT * FROM read_csv_auto('{DATA_PATH}Customer.csv', header=True);\n",
        "      \"\"\")\n",
        "  print(\"customers_raw loaded\")\n",
        "  #currency\n",
        "  con.execute(f\"\"\"\n",
        "          CREATE OR REPLACE TABLE currency_raw AS\n",
        "          SELECT * FROM read_csv_auto('{DATA_PATH}Currency.csv', header=True);\n",
        "      \"\"\")\n",
        "  print(\"currency_raw loaded\")\n",
        "  #store_territory\n",
        "  con.execute(f\"\"\"\n",
        "          CREATE OR REPLACE TABLE store_territory_raw AS\n",
        "          SELECT * FROM read_csv_auto('{DATA_PATH}Store_Territory.csv', header=True);\n",
        "      \"\"\")\n",
        "  print(\"Store_Territory loaded\")\n",
        "\n",
        "  # Read dinamically both product sales files to be unified into a single table\n",
        "  con.execute(f\"\"\"\n",
        "          CREATE OR REPLACE TABLE product_sales_raw AS\n",
        "          SELECT * FROM read_csv_auto('{DATA_PATH}Product_Sales_*.csv', header=True);\n",
        "      \"\"\")\n",
        "\n",
        "  print(\"product_sales_raw loaded\")\n",
        "\n",
        "except Exception as e:\n",
        "  print(f\"Ingestion process failed: {str(e)}\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 118,
          "referenced_widgets": [
            "6068d952ee6b407cbbaaec56c283c094",
            "eb0cbdfd7e054e5da55f9c9740a6239f",
            "39fb0a2c1e2149d2aac9f4c0e4adb3ba"
          ]
        },
        "id": "KnNFm0NzeVlC",
        "outputId": "9f3a8f42-6bf1-4aeb-e89e-c8abbf6a29c9"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "customers_raw loaded\n",
            "currency_raw loaded\n",
            "Store_Territory loaded\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "6068d952ee6b407cbbaaec56c283c094"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "product_sales_raw loaded\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# --- Verification Check ---\n",
        "tablas = ['customers_raw', 'currency_raw', 'store_territory_raw', 'product_sales_raw']\n",
        "\n",
        "for tabla in tablas:\n",
        "    count = con.execute(f\"SELECT COUNT(*) FROM {tabla}\").fetchone()[0]\n",
        "    print(f\"Table: {tabla} | Total Records: {count:,}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "-aV4oBtOdas9",
        "outputId": "a0a98ed5-4542-4bb0-9638-74eddbd696a4"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Table: customers_raw | Total Records: 37,738\n",
            "Table: currency_raw | Total Records: 28\n",
            "Table: store_territory_raw | Total Records: 312\n",
            "Table: product_sales_raw | Total Records: 365,256\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "test_query = con.sql(\"\"\"\n",
        "    SELECT *\n",
        "    FROM fact_sales\n",
        "    LIMIT 3;\n",
        "\"\"\").df()\n",
        "display(test_query)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 215
        },
        "id": "2BNHuSc2JdLG",
        "outputId": "2333f351-572e-4fdd-cedd-7c8c717b211d"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   ID_Sales  ID_Channel  ID_Store  ID_Product  ID_Promotion  ID_Currency  \\\n",
              "0        12           1       119         543             1            1   \n",
              "1        53           1       121         709             1            1   \n",
              "2        82           1        18         590             3            1   \n",
              "\n",
              "        Date  SalesQuantity  ReturnQuantity  ReturnAmount  DiscountQuantity  \\\n",
              "0 2020-04-29             10               0           0.0                 0   \n",
              "1 2020-04-19             10               0           0.0                 0   \n",
              "2 2020-07-10             12               0           0.0                 2   \n",
              "\n",
              "   DiscountAmount  TotalCost  SalesAmount  NetQuantity  NetProfit  \\\n",
              "0             0.0     1167.5       2290.0           10     1122.5   \n",
              "1             0.0      533.4       1160.0           10      626.6   \n",
              "2           199.8     5512.8      11788.2           12     6275.4   \n",
              "\n",
              "   ProfitMargin  \n",
              "0      0.490175  \n",
              "1      0.540172  \n",
              "2      0.532346  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-e4dba9d7-41ad-4cc2-81c9-49d66f9b08e1\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>ID_Sales</th>\n",
              "      <th>ID_Channel</th>\n",
              "      <th>ID_Store</th>\n",
              "      <th>ID_Product</th>\n",
              "      <th>ID_Promotion</th>\n",
              "      <th>ID_Currency</th>\n",
              "      <th>Date</th>\n",
              "      <th>SalesQuantity</th>\n",
              "      <th>ReturnQuantity</th>\n",
              "      <th>ReturnAmount</th>\n",
              "      <th>DiscountQuantity</th>\n",
              "      <th>DiscountAmount</th>\n",
              "      <th>TotalCost</th>\n",
              "      <th>SalesAmount</th>\n",
              "      <th>NetQuantity</th>\n",
              "      <th>NetProfit</th>\n",
              "      <th>ProfitMargin</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>12</td>\n",
              "      <td>1</td>\n",
              "      <td>119</td>\n",
              "      <td>543</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>2020-04-29</td>\n",
              "      <td>10</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1167.5</td>\n",
              "      <td>2290.0</td>\n",
              "      <td>10</td>\n",
              "      <td>1122.5</td>\n",
              "      <td>0.490175</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>53</td>\n",
              "      <td>1</td>\n",
              "      <td>121</td>\n",
              "      <td>709</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>2020-04-19</td>\n",
              "      <td>10</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>533.4</td>\n",
              "      <td>1160.0</td>\n",
              "      <td>10</td>\n",
              "      <td>626.6</td>\n",
              "      <td>0.540172</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>82</td>\n",
              "      <td>1</td>\n",
              "      <td>18</td>\n",
              "      <td>590</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>2020-07-10</td>\n",
              "      <td>12</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>2</td>\n",
              "      <td>199.8</td>\n",
              "      <td>5512.8</td>\n",
              "      <td>11788.2</td>\n",
              "      <td>12</td>\n",
              "      <td>6275.4</td>\n",
              "      <td>0.532346</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-e4dba9d7-41ad-4cc2-81c9-49d66f9b08e1')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-e4dba9d7-41ad-4cc2-81c9-49d66f9b08e1 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-e4dba9d7-41ad-4cc2-81c9-49d66f9b08e1');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_283c13e6-519b-400d-89a2-8c11e77fc5bb\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('test_query')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_283c13e6-519b-400d-89a2-8c11e77fc5bb button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('test_query');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "test_query",
              "summary": "{\n  \"name\": \"test_query\",\n  \"rows\": 3,\n  \"fields\": [\n    {\n      \"column\": \"ID_Sales\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 35,\n        \"min\": 12,\n        \"max\": 82,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          12,\n          53,\n          82\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ID_Channel\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 1,\n        \"max\": 1,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ID_Store\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 58,\n        \"min\": 18,\n        \"max\": 121,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          119\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ID_Product\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 85,\n        \"min\": 543,\n        \"max\": 709,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          543\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ID_Promotion\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 3,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ID_Currency\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 1,\n        \"max\": 1,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Date\",\n      \"properties\": {\n        \"dtype\": \"date\",\n        \"min\": \"2020-04-19 00:00:00\",\n        \"max\": \"2020-07-10 00:00:00\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"2020-04-29 00:00:00\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SalesQuantity\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 10,\n        \"max\": 12,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          12\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ReturnQuantity\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ReturnAmount\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0,\n        \"max\": 0.0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"DiscountQuantity\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 0,\n        \"max\": 2,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"DiscountAmount\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 115.35458378408723,\n        \"min\": 0.0,\n        \"max\": 199.8,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          199.8\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"TotalCost\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2710.4163044324637,\n        \"min\": 533.4,\n        \"max\": 5512.8,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          1167.5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SalesAmount\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5837.398656936153,\n        \"min\": 1160.0,\n        \"max\": 11788.2,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          2290.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"NetQuantity\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 10,\n        \"max\": 12,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          12\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"NetProfit\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3128.024846981452,\n        \"min\": 626.6,\n        \"max\": 6275.400000000001,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          1122.5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ProfitMargin\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.026893125647311656,\n        \"min\": 0.490174672489083,\n        \"max\": 0.5401724137931034,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          0.490174672489083\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "## **Dimension Modeling & Core ELT**\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "BddvbMzdodAr"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "### **Quality, Cleaning and Transformation (Silver)**\n",
        "\n",
        "This section implements data cleaning and standardization rules to transform raw data into normalized datasets.\n",
        "\n",
        "Four different methods will normalize data by removing duplicate columns and duplicate data bases on primary keys from every table, handling missing values by filling null values with expected values dependig on value types and casting data types to get data in a valid format to be used.\n",
        "\n",
        "The last method will load normalized data into new tables to get a standarized data layer"
      ],
      "metadata": {
        "id": "8J0kM9LIl4cy"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# ==============================================================================\n",
        "# Normalization methods\n",
        "# ==============================================================================\n",
        "\n",
        "import pandas as pd\n",
        "import duckdb\n",
        "\n",
        "def handle_duplicate_columns(df: pd.DataFrame) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    Scans the DataFrame for columns auto-suffixed with '_1'\n",
        "    Compares data contents with the original base column, if contents match exactly, the redundant column is dropped.\n",
        "    \"\"\"\n",
        "    columns_to_drop = []\n",
        "\n",
        "    for col in df.columns:\n",
        "        if col.startswith(\"EmployeeKey\"):\n",
        "            columns_to_drop.append(col)\n",
        "\n",
        "    for col in df.columns:\n",
        "        if col.endswith('_1'):\n",
        "            base_col = col[:-2]\n",
        "            if base_col in df.columns:\n",
        "                if df[base_col].equals(df[col]):\n",
        "                    columns_to_drop.append(col)\n",
        "\n",
        "    # Execute drops\n",
        "    if columns_to_drop:\n",
        "        df = df.drop(columns=columns_to_drop)\n",
        "        print(f\"  Removed exact duplicate columns: {columns_to_drop}\")\n",
        "\n",
        "    return df\n",
        "\n",
        "def remove_duplicates(df: pd.DataFrame, primary_key: str, order_by_col: str = None) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    Removes duplicate records based on a primary key.\n",
        "    If an order_by_col is provided, it keeps the latest record.\n",
        "    \"\"\"\n",
        "    if order_by_col and order_by_col in df.columns:\n",
        "        # Convert to datetime temporarily to ensure accurate sorting sequence\n",
        "        temp_date = pd.to_datetime(df[order_by_col], errors='coerce')\n",
        "        df = df.iloc[temp_date.argsort()[::-1]]\n",
        "\n",
        "    df_cleaned = df.drop_duplicates(subset=[primary_key], keep='first')\n",
        "    return df_cleaned\n",
        "\n",
        "\n",
        "def handle_missing_values(df: pd.DataFrame, string_fill: str = 'Unknown', numeric_fill: float = 0.0) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    Inspects columns and handles missing values based on data types.\n",
        "    \"\"\"\n",
        "    for col in df.columns:\n",
        "        # Check if the column is categorical/object text\n",
        "        if df[col].dtype == 'object' or isinstance(df[col].dtype, pd.CategoricalDtype):\n",
        "            df[col] = df[col].fillna(string_fill)\n",
        "        # Check if the column is numeric\n",
        "        elif pd.api.types.is_numeric_dtype(df[col]):\n",
        "            df[col] = df[col].fillna(numeric_fill)\n",
        "\n",
        "    return df\n",
        "\n",
        "\n",
        "def cast_data_types(df: pd.DataFrame, type_mapping: dict) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    Casts dataframe columns to specified data types.\n",
        "    Supports specific handling for date format\n",
        "    \"\"\"\n",
        "    for col, data_type in type_mapping.items():\n",
        "        if col in df.columns:\n",
        "            if data_type == 'date':\n",
        "                df[col] = pd.to_datetime(df[col], errors='coerce').dt.date\n",
        "            else:\n",
        "                df[col] = df[col].astype(data_type)\n",
        "    return df\n",
        "\n"
      ],
      "metadata": {
        "id": "_-_R8KMBnmdo"
      },
      "execution_count": 8,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ==============================================================================\n",
        "# Orchestration process to apply normalization methods and create cleansed layer\n",
        "# ==============================================================================\n",
        "\n",
        "def cleaning_process(con: duckdb.DuckDBPyConnection, source_table: str, target_table: str,\n",
        "                        primary_key: str, order_by_col: str = None, type_mapping: dict = None):\n",
        "\n",
        "\n",
        "    print(f\"Processing transformations from: {source_table} to {target_table}\")\n",
        "\n",
        "    # Extract data from DB raw staging layer to dataframes\n",
        "    df = con.execute(f\"SELECT * FROM {source_table}\").df()\n",
        "\n",
        "    # Apply standardisation methods\n",
        "    df = handle_duplicate_columns(df)\n",
        "    df = remove_duplicates(df, primary_key=primary_key, order_by_col=order_by_col)\n",
        "    df = handle_missing_values(df)\n",
        "    df = cast_data_types(df, type_mapping)\n",
        "\n",
        "    # Load processed dataframe back into DB cleansed layer\n",
        "    con.register('tmp_df', df)\n",
        "    con.execute(f\"CREATE OR REPLACE TABLE {target_table} AS SELECT * FROM tmp_df\")\n",
        "    con.unregister('tmp_df')\n",
        "\n",
        "    print(f\"Successfully loaded '{target_table}'\")\n",
        "\n"
      ],
      "metadata": {
        "id": "mWTnCMcUhjBG"
      },
      "execution_count": 9,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "try:\n",
        "    # Schema mappings for each table\n",
        "    customer_types = {\n",
        "        'CustomerKey': 'int', 'GeographyKey': 'int', 'FirstName': 'str', 'LastName': 'str','BirthDate': 'date', 'MaritalStatus': 'str', 'Gender': 'str', 'YearlyIncome': 'float',\n",
        "        'TotalChildren': 'int', 'NumberChildrenAtHome': 'int', 'Education': 'str','Occupation': 'str', 'HouseOwnerFlag': 'int', 'NumberCarsOwned': 'int', 'modified_date': 'date'\n",
        "    }\n",
        "\n",
        "    currency_types = {\n",
        "      'CurrencyKey': 'int', 'CurrencyName': 'str', 'CurrencyDescription': 'str'\n",
        "    }\n",
        "\n",
        "    store_types = {\n",
        "      'StoreKey': 'int', 'GeographyKey': 'int', 'StoreManager': 'str', 'StoreType': 'str','StoreName': 'str', 'Status': 'str', 'OpenDate': 'date', 'CloseDate': 'date',\n",
        "      'EntityKey': 'int', 'StorePhone': 'str', 'StoreFax': 'str', 'CloseReason': 'str','EmployeeCount': 'int', 'SellingAreaSize': 'float', 'LastRemodelDate': 'date',\n",
        "      'SalesTerritoryKey': 'int', 'SalesTerritoryName': 'str','SalesTerritoryRegion': 'str', 'SalesTerritoryCountry': 'str', 'SalesTerritoryGroup': 'str',\n",
        "      'SalesTerritoryLevel': 'str', 'SalesTerritoryManager': 'int', 'Status_1': 'str'\n",
        "    }\n",
        "\n",
        "    sales_types = {\n",
        "      'SalesKey': 'int', 'DateKey': 'date', 'channelKey': 'int', 'StoreKey': 'int', 'ProductKey': 'int', 'PromotionKey': 'int', 'CurrencyKey': 'int','UnitCost': 'float',\n",
        "      'UnitPrice': 'float', 'SalesQuantity': 'int','ReturnQuantity': 'int', 'ReturnAmount': 'float', 'DiscountQuantity': 'int','DiscountAmount': 'float', 'TotalCost': 'float',\n",
        "      'SalesAmount': 'float', 'ProductName': 'str', 'ProductDescription': 'str','ProductSubcategoryKey': 'int', 'Manufacturer': 'str', 'BrandName': 'str', 'ClassID': 'str',\n",
        "      'ClassName': 'str', 'StyleID': 'int', 'StyleName': 'str','ColorID': 'int', 'ColorName': 'str', 'Weight': 'float', 'WeightUnitMeasureID': 'str', 'UnitOfMeasureID': 'int',\n",
        "      'UnitOfMeasureName': 'str', 'StockTypeID': 'int', 'StockTypeName': 'str', 'AvailableForSaleDate': 'date', 'Status': 'str'\n",
        "    }\n",
        "\n",
        "    # Execute orchestrator function across all target datasets\n",
        "    cleaning_process(con, 'customers_raw', 'customers_cleansed',\n",
        "                        primary_key='CustomerKey', order_by_col='modified_date', type_mapping=customer_types)\n",
        "\n",
        "    cleaning_process(con, 'currency_raw', 'currency_cleansed',\n",
        "                        primary_key='CurrencyKey', type_mapping=currency_types)\n",
        "\n",
        "    cleaning_process(con, 'store_territory_raw', 'store_territory_cleansed',\n",
        "                        primary_key='StoreKey', type_mapping=store_types)\n",
        "\n",
        "    cleaning_process(con, 'product_sales_raw', 'product_sales_cleansed',\n",
        "                        primary_key='SalesKey', type_mapping=sales_types)\n",
        "\n",
        "    print(\"All cleansed tables have been processed and loaded\")\n",
        "\n",
        "except Exception as e:\n",
        "    print(f\"❌ Pipeline failed: {str(e)}\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cc5_VJi4h1W6",
        "outputId": "e795b0d3-efb7-45ea-b2c6-020339c0976e"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Processing transformations from: customers_raw to customers_cleansed\n",
            "Successfully loaded 'customers_cleansed'\n",
            "Processing transformations from: currency_raw to currency_cleansed\n",
            "Successfully loaded 'currency_cleansed'\n",
            "Processing transformations from: store_territory_raw to store_territory_cleansed\n",
            "  Removed exact duplicate columns: ['EmployeeKey', 'EmployeeKey_1']\n",
            "Successfully loaded 'store_territory_cleansed'\n",
            "Processing transformations from: product_sales_raw to product_sales_cleansed\n",
            "  Removed exact duplicate columns: ['ProductKey_1', 'UnitCost_1', 'UnitPrice_1']\n",
            "Successfully loaded 'product_sales_cleansed'\n",
            "All cleansed tables have been processed and loaded\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Validation check\n",
        "cleansed_tables = [\n",
        "    'customers_cleansed',\n",
        "    'currency_cleansed',\n",
        "    'store_territory_cleansed',\n",
        "    'product_sales_cleansed'\n",
        "]\n",
        "\n",
        "for table in cleansed_tables:\n",
        "    # Get row count\n",
        "    count = con.execute(f\"SELECT COUNT(*) FROM {table}\").fetchone()[0]\n",
        "    # Get column count\n",
        "    col_count = len(con.execute(f\"SELECT * FROM {table} LIMIT 1\").df().columns)\n",
        "\n",
        "    print(f\"{table} | Columns: {col_count} | Total Records: {count:,}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "8MFwxHbGxA0M",
        "outputId": "4db42608-5f91-4b01-8f8d-f2420f908fa3"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "customers_cleansed | Columns: 15 | Total Records: 18,869\n",
            "currency_cleansed | Columns: 3 | Total Records: 28\n",
            "store_territory_cleansed | Columns: 23 | Total Records: 306\n",
            "product_sales_cleansed | Columns: 35 | Total Records: 208,201\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "### **Dimensional Modeling (Gold)**\n",
        "\n",
        "This final section will create an star schema model based on cleansed tables with some metrics created to be used in BI tools\n",
        "\n",
        "As data product and sales product are in the same table `product_sales_cleansed`, to avoid data redundancy, the strategy is create a dimensional table with product data.\n",
        "In order to improve analytical information in the model, new KPIs are computed at the row level within the `fact_sales` table: `NetQuantity` calculated as `SalesQuantity - ReturnQuantity`, `NetProfit` calculated as `SalesAmount - TotalCost`and `ProfitMargin` as ratio of Net Profit to total Sales Amount.\n",
        "\n",
        "The Final Star Schema Entities will be `dim_customer`, `dim_currency`, `dim_store_territory`, `dim_product`, and `fact_sales`."
      ],
      "metadata": {
        "id": "YySSArIWET0w"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "try:\n",
        "\n",
        "    # Dimension Customer\n",
        "\n",
        "    con.execute(\"\"\"\n",
        "        CREATE TABLE dim_customer AS\n",
        "        SELECT\n",
        "            CustomerKey AS ID_Customer,\n",
        "            GeographyKey AS ID_Geography,\n",
        "            FirstName,\n",
        "            LastName,\n",
        "            BirthDate,\n",
        "            MaritalStatus,\n",
        "            Gender,\n",
        "            YearlyIncome\n",
        "        FROM customers_cleansed;\n",
        "    \"\"\")\n",
        "\n",
        "    print(\"Dimension created: 'dim_customer'\")\n",
        "\n",
        "\n",
        "    # Dimension Currency\n",
        "\n",
        "    con.execute(\"\"\"\n",
        "        CREATE OR REPLACE TABLE dim_currency AS\n",
        "        SELECT\n",
        "        CurrencyKey as ID_Currency,\n",
        "        CurrencyName,\n",
        "        CurrencyDescription\n",
        "        FROM currency_cleansed;\n",
        "    \"\"\")\n",
        "    print(\"Dimension created: 'dim_currency'\")\n",
        "\n",
        "\n",
        "    # Dimension Store territory\n",
        "\n",
        "    con.execute(\"\"\"\n",
        "        CREATE OR REPLACE TABLE dim_store_territory AS\n",
        "        SELECT\n",
        "            StoreKey AS ID_Store,\n",
        "            StoreManager AS ID_StoreManager,\n",
        "            SalesTerritoryKey AS ID_SalesTerritory,\n",
        "            SalesTerritoryManager AS ID_TerritoryManager,\n",
        "            EntityKey AS ID_Entity,\n",
        "            StoreName,\n",
        "            StoreType,\n",
        "            Status,\n",
        "            OpenDate,\n",
        "            CloseDate,\n",
        "            EmployeeCount,\n",
        "            SalesTerritoryName,\n",
        "            SalesTerritoryRegion,\n",
        "            SalesTerritoryCountry,\n",
        "            SalesTerritoryGroup\n",
        "        FROM store_territory_cleansed;\n",
        "    \"\"\")\n",
        "    print(\"Dimension created: 'dim_store_territory'\")\n",
        "\n",
        "\n",
        "    # Dimension Product\n",
        "\n",
        "    con.execute(\"\"\"\n",
        "        CREATE OR REPLACE TABLE dim_product AS\n",
        "        SELECT DISTINCT\n",
        "            ProductKey AS ID_Product,\n",
        "            ProductSubcategoryKey AS ID_ProductSubcategory,\n",
        "            ProductName,\n",
        "            ProductDescription,\n",
        "            Manufacturer,\n",
        "            BrandName,\n",
        "            ClassName,\n",
        "            UnitCost,\n",
        "            UnitPrice,\n",
        "            Status AS ProductStatus,\n",
        "            AvailableForSaleDate\n",
        "        FROM product_sales_cleansed\n",
        "        WHERE ProductKey IS NOT NULL;\n",
        "    \"\"\")\n",
        "    print(\"Dimension created: 'dim_product'\")\n",
        "\n",
        "\n",
        "    # Fact table Sales\n",
        "\n",
        "    con.execute(\"\"\"\n",
        "        CREATE OR REPLACE TABLE fact_sales AS\n",
        "        SELECT\n",
        "            SalesKey AS ID_Sales,\n",
        "            channelKey AS ID_Channel,\n",
        "            StoreKey AS ID_Store,\n",
        "            ProductKey AS ID_Product,\n",
        "            PromotionKey AS ID_Promotion,\n",
        "            CurrencyKey AS ID_Currency,\n",
        "            DateKey AS Date,\n",
        "            SalesQuantity,\n",
        "            ReturnQuantity,\n",
        "            ReturnAmount,\n",
        "            DiscountQuantity,\n",
        "            DiscountAmount,\n",
        "            TotalCost,\n",
        "            SalesAmount,\n",
        "            -- Tailored KPIs\n",
        "            (SalesQuantity - ReturnQuantity) AS NetQuantity,\n",
        "            (SalesAmount - TotalCost) AS NetProfit,\n",
        "            CASE\n",
        "                WHEN SalesAmount > 0 THEN (SalesAmount - TotalCost) / SalesAmount\n",
        "                ELSE 0\n",
        "            END AS ProfitMargin\n",
        "\n",
        "        FROM product_sales_cleansed;\n",
        "    \"\"\")\n",
        "    print(\"Fact table created: 'fact_sales'\")\n",
        "\n",
        "    print(\" Dimensional Model completed\")\n",
        "\n",
        "except Exception as e:\n",
        "    print(f\"Error during Dimensional Model creation: {str(e)}\")"
      ],
      "metadata": {
        "id": "6t4HHRSWEa2i",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "666820ad-3d8c-4915-d139-b54fb3d1b8f5"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dimension created: 'dim_customer'\n",
            "Dimension created: 'dim_currency'\n",
            "Dimension created: 'dim_store_territory'\n",
            "Dimension created: 'dim_product'\n",
            "Fact table created: 'fact_sales'\n",
            " Dimensional Model completed\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Validation check\n",
        "\n",
        "dimensional_tables = [\n",
        "    'dim_customer',\n",
        "    'dim_currency',\n",
        "    'dim_store_territory',\n",
        "    'dim_product',\n",
        "    'fact_sales'\n",
        "]\n",
        "\n",
        "for table in dimensional_tables:\n",
        "    # Get row count\n",
        "    count = con.execute(f\"SELECT COUNT(*) FROM {table}\").fetchone()[0]\n",
        "    # Get column count\n",
        "    col_count = len(con.execute(f\"SELECT * FROM {table} LIMIT 1\").df().columns)\n",
        "\n",
        "    print(f\"{table} | Columns: {col_count} | Total Records: {count:,}\")\n",
        "\n",
        "print(\"Tailored KPIs Preview\")\n",
        "preview_kpis = con.execute(\"\"\"\n",
        "    SELECT ID_Sales, SalesAmount, TotalCost, NetProfit, ROUND(ProfitMargin, 2) as Margin\n",
        "    FROM fact_sales\n",
        "    WHERE NetProfit > 0\n",
        "    LIMIT 3\n",
        "\"\"\").df()\n",
        "display(preview_kpis)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 247
        },
        "id": "XLQNr7EXPZ_2",
        "outputId": "31f04e15-7167-419f-8460-4b880f2de70c"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "dim_customer | Columns: 8 | Total Records: 18,869\n",
            "dim_currency | Columns: 3 | Total Records: 28\n",
            "dim_store_territory | Columns: 15 | Total Records: 306\n",
            "dim_product | Columns: 11 | Total Records: 718\n",
            "fact_sales | Columns: 17 | Total Records: 208,201\n",
            "Tailored KPIs Preview\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   ID_Sales  SalesAmount  TotalCost  NetProfit  Margin\n",
              "0        12       2290.0     1167.5     1122.5    0.49\n",
              "1        53       1160.0      533.4      626.6    0.54\n",
              "2        82      11788.2     5512.8     6275.4    0.53"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-fa63f3fb-b347-4860-bcf8-33e9e4a9e2ae\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>ID_Sales</th>\n",
              "      <th>SalesAmount</th>\n",
              "      <th>TotalCost</th>\n",
              "      <th>NetProfit</th>\n",
              "      <th>Margin</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>12</td>\n",
              "      <td>2290.0</td>\n",
              "      <td>1167.5</td>\n",
              "      <td>1122.5</td>\n",
              "      <td>0.49</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>53</td>\n",
              "      <td>1160.0</td>\n",
              "      <td>533.4</td>\n",
              "      <td>626.6</td>\n",
              "      <td>0.54</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>82</td>\n",
              "      <td>11788.2</td>\n",
              "      <td>5512.8</td>\n",
              "      <td>6275.4</td>\n",
              "      <td>0.53</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-fa63f3fb-b347-4860-bcf8-33e9e4a9e2ae')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-fa63f3fb-b347-4860-bcf8-33e9e4a9e2ae button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-fa63f3fb-b347-4860-bcf8-33e9e4a9e2ae');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_eeda3f58-970a-4c39-b4ae-29a655816219\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('preview_kpis')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_eeda3f58-970a-4c39-b4ae-29a655816219 button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('preview_kpis');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "preview_kpis",
              "summary": "{\n  \"name\": \"preview_kpis\",\n  \"rows\": 3,\n  \"fields\": [\n    {\n      \"column\": \"ID_Sales\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 35,\n        \"min\": 12,\n        \"max\": 82,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          12,\n          53,\n          82\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SalesAmount\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5837.398656936153,\n        \"min\": 1160.0,\n        \"max\": 11788.2,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          2290.0,\n          1160.0,\n          11788.2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"TotalCost\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2710.4163044324637,\n        \"min\": 533.4,\n        \"max\": 5512.8,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          1167.5,\n          533.4,\n          5512.8\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"NetProfit\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3128.024846981452,\n        \"min\": 626.6,\n        \"max\": 6275.400000000001,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          1122.5,\n          626.6,\n          6275.400000000001\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Margin\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.026457513110645932,\n        \"min\": 0.49,\n        \"max\": 0.54,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          0.49,\n          0.54,\n          0.53\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}